crossdev:  Added s390 Support; tested to build kernel cross-compiler crossdev-status: Added s390 display; Major code cleanup to allow the table to be resized at will and not generate messed up output.

diff --git a/users/kumba/crossdev/crossdev-status b/users/kumba/crossdev/crossdev-status
--- a/users/kumba/crossdev/crossdev-status
+++ b/users/kumba/crossdev/crossdev-status
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/kumba/crossdev/Attic/crossdev-status,v 1.2 2004/02/26 08:03:52 kumba Exp $
+# $Header: /var/cvsroot/gentoo/users/kumba/crossdev/Attic/crossdev-status,v 1.3 2004/03/06 11:15:11 kumba Exp $
 
 
 #// Script Variables
@@ -21,7 +21,7 @@ fi
 
 
 #// My Version
-MYVERSION="0.3"
+MYVERSION="0.5"
 
 #// Do we want colors?
 if [ "${USE_COLOR}" = "yes" ]; then
@@ -73,9 +73,9 @@ berror() {
 getStatus() {
 
 	#// Valid call
-	if [ -z "${*}" ]; then
-		echo "Error in getStatus()!"
-	fi
+#	if [ -z "${*}" ]; then
+#		echo "Error in getStatus()!"
+#	fi
 
 	#// Determine the current status
 	case "${1}" in
@@ -108,49 +108,53 @@ displayStatus() {
 	#// - = invalid (i.e., the host & target arch are the same)
 	#// X = failure (faild to build even a kernel toolchain (likely died in gcc-bootstrap))
 
-	#//					    0 1 2 3 4 5 6 7 8 9 0
-	#//			  1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1 2
-	#//---------------------------------------------------------------
-	declare -a	   alpha=(- 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 1
-	declare -a	   amd64=(0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 2
-	declare -a	     arm=(0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 3
-	declare -a	    cris=(0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 4
-	declare -a	    hppa=(0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 5
-	declare -a	    i486=(0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 6
-	declare -a	    i586=(0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0) # 7
-	declare -a	    i686=(K F 0 K 0 K F - X K F K F K F K F K K 0) # 8
-	declare -a	    ia64=(0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0) # 9
-	declare -a	    m68k=(0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0) # 10
-	declare -a	    mips=(0 0 0 0 0 0 0 0 0 0 - K 0 0 0 0 0 0 0 0) # 11
-	declare -a	  mips64=(0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0) # 12
-	declare -a	  mipsel=(0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0) # 13
-	declare -a	mips64el=(0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0) # 14
-	declare -a	     ppc=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0) # 15
-	declare -a	   ppc64=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0) # 16
-	declare -a	ppc_eabi=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0) # 17
-	declare -a	      sh=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0) # 18
-	declare -a	   sparc=(0 F 0 0 0 0 0 X 0 0 F 0 F 0 X 0 0 0 - K) # 19
-	declare -a	 sparc64=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 F -) # 20
-	#//---------------------------------------------------------------
+	#//					    0 1 2 3 4 5 6 7 8 9 0 1
+	#//			  1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1 2 2
+	#//-----------------------------------------------------------------
+	declare -a	   alpha=(- 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 1
+	declare -a	   amd64=(0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 2
+	declare -a	     arm=(0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 3
+	declare -a	    cris=(0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 4
+	declare -a	    hppa=(0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 5
+	declare -a	    i486=(0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 6
+	declare -a	    i586=(0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0 0 0) # 7
+	declare -a	    i686=(K F 0 K 0 K F - X K F K F K F K F K 0 K K) # 8
+	declare -a	    ia64=(0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0 0) # 9
+	declare -a	    m68k=(0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0 0 0) # 10
+	declare -a	    mips=(0 0 0 0 0 0 0 0 0 0 - K 0 0 0 0 0 0 0 0 0) # 11
+	declare -a	  mips64=(0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0 0) # 12
+	declare -a	  mipsel=(0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0 0) # 13
+	declare -a	mips64el=(0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0 0) # 14
+	declare -a	     ppc=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0 0) # 15
+	declare -a	   ppc64=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0 0) # 16
+	declare -a	ppc_eabi=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0 0) # 17
+	declare -a	    s390=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0 0) # 18
+	declare -a	      sh=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 - 0 0) # 19
+	declare -a	   sparc=(0 F 0 0 0 0 0 X 0 0 F 0 F 0 X 0 0 0 0 - K) # 20
+	declare -a	 sparc64=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 F -) # 21
+	#//-----------------------------------------------------------------
 
 
-	declare -a archlist=(alpha amd64 arm cris hppa i486 i586 \
-			     i686 ia64 m68k mips mips64 mipsel \
-			     mips64el ppc ppc64 ppc_eabi sh \
-			     sparc sparc64)
+	#// Arch master list
+	declare -a archlist=(alpha amd64 arm cris hppa i486 i586 i686 ia64 m68k \
+			     mips mips64 mipsel mips64el ppc ppc64 ppc_eabi s390 \
+			     sh sparc sparc64)
 
 	#// Misc variables controlling output
-	local hi ti1 ti2 # host index, target index (loop 1 & 2)
+	local hi ti1 ti2 x # host index, target index (loop 1 & 2), temp var
 	local HOST_ARCH TARG_ARCH
 	local arch_arr_val # read arch arrays dynamically
-	local tab_char
+	local tab_char c1_tab_char
 
 	#// Number of archs per line
-	#// Leave this alone, as it really messes the output up
-	#// It's here because I don't like hardcoding values
-	local archs_per_line=5
+	local archs_per_line=6
 
-	#// Maximum num of chars a target arch name can have
+	#// Minimum num of chars a target arch name needs in the first column
+	#// If less than a certain value, we append a tab character to
+	#// make the output look nice
+	local c1_min_char=5
+
+	#// Maximum num of chars a target arch name can have in remaining columns
 	#// If less than a certain value, we append a tab character to
 	#// make the output look nice
 	local t_max_char=8
@@ -173,14 +177,12 @@ displayStatus() {
 		HOST_ARCH=${archlist[${hosti}]}
 
 		#// #// If strlen <= ${h_min_char} characters, append a tab character
-		if [ ${#HOST_ARCH} -le ${h_min_char} ]; then
-			tab_char="\t"
-		else
-			tab_char=""
-		fi
+		[ ${#HOST_ARCH} -le ${h_min_char} ] && tab_char="\t" || tab_char=""
 
 		#// Print the main arch
-		echo -e "    ${GREEN}${HOST_ARCH/_/-}:${XX}${tab_char}\t-------------------------------------------------------------------------------"
+		echo -ne "    ${GREEN}${HOST_ARCH/_/-}:${XX}${tab_char}\t  ---------------------"
+		for x in $(seq 1 1 $((${archs_per_line} - 2))); do echo -en "----------------";	done
+		[ ${archs_per_line} -ne 1 ] && echo -e "---------------" || echo -e ""
 
 		#// For each host arch, list what target toolchains can be built
 		for ti1 in $(seq 0 ${archs_per_line} $((${#archlist[*]} - 1))); do
@@ -188,16 +190,12 @@ displayStatus() {
 			arch_arr_val="${HOST_ARCH}[${ti1}]"
 			arch_arr_val="${!arch_arr_val}"
 
-			#// If strlen < ${t_max_char} characters, append a tab character
-			if [ ${#TARG_ARCH} -lt ${t_max_char} ]; then
-				tab_char="\t"
-			else
-				tab_char=""
-			fi
+			#// If strlen > ${c1_min_char} characters, append two tab characters
+			[ ${#TARG_ARCH} -lt ${c1_min_char} ] && c1_tab_char="\t" || c1_tab_char=""
 
 			#// Display first target-arch name
 			getStatus "${arch_arr_val}"
-			echo -ne "\t\t| ${WHITE}${TARG_ARCH/_/-}${XX}${tab_char}${TMPSTATBIT} |"
+			echo -ne "\t\t | ${WHITE}${TARG_ARCH/_/-}${XX}${c1_tab_char}\t${TMPSTATBIT} |"
 
 			#// Display remaining target-arch names
 			for ti2 in $(seq $((ti1 + 1)) $((ti1 + archs_per_line - 1))); do
@@ -206,11 +204,7 @@ displayStatus() {
 				arch_arr_val="${!arch_arr_val}"
 
 				#// If strlen < ${t_max_char} characters, append a tab character
-				if [ ${#TARG_ARCH} -lt ${t_max_char} ]; then
-					tab_char="\t"
-				else
-					tab_char=""
-				fi
+				[ ${#TARG_ARCH} -lt ${t_max_char} ] && tab_char="\t" ||	tab_char=""
 
 				if [ ! -z "${TARG_ARCH}" ]; then
 					getStatus "${arch_arr_val}"
@@ -224,15 +218,19 @@ displayStatus() {
 	done
 
 
+	#// Print the last line
+	echo -en "    \t\t  ---------------------"
+	for x in $(seq 1 1 $((${archs_per_line} - 2))); do echo -en "----------------";	done
+	[ ${archs_per_line} -ne 1 ] && echo -e "---------------" || echo -e ""
+
 	#// Print the legend
-	echo -e "    \t\t-------------------------------------------------------------------------------"
 	echo -e ""
 	echo -e "${WHITE}Legend:${XX}"
-	echo -en "\t${BLUE}[${PURPLE} ? ${BLUE}]${WHITE} - Toolchain untested on this arch."
+	echo -en "\t\t ${BLUE}[${PURPLE} ? ${BLUE}]${WHITE} - Toolchain untested on this arch."
 	echo -e "\t${BLUE}[${YELLOW} K ${BLUE}]${WHITE} - Will build a kernel-only toolchain.${XX}"
-	echo -en "\t${BLUE}[${GREEN} F ${BLUE}]${WHITE} - Will build a full toolchain. (C & C++)"
+	echo -en "\t\t ${BLUE}[${GREEN} F ${BLUE}]${WHITE} - Will build a full toolchain. (C & C++)"
 	echo -e "\t${BLUE}[${CYAN} - ${BLUE}]${WHITE} - Invalid/Same host & target arch.${XX}"
-	echo -e "\t${BLUE}[${RED} * ${BLUE}]${WHITE} - Failed to build a toolchain${XX}"
+	echo -e "\t\t ${BLUE}[${RED} * ${BLUE}]${WHITE} - Failed to build a toolchain${XX}"
 	echo -e ""
 	echo -e "${WHITE}If you get a new combination to work please inform us at ${CYAN}http://bugs.gentoo.org/${XX}"
 	echo -e ""
