Check for presence of dialog before running.  Suggestion made by Markus Saarinen <heroine@saunalahti.fi> in bug #134486.

diff --git a/src/livecd-tools/net-setup b/src/livecd-tools/net-setup
--- a/src/livecd-tools/net-setup
+++ b/src/livecd-tools/net-setup
@@ -1,13 +1,19 @@
 #!/bin/bash
 # Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/src/livecd-tools/net-setup,v 1.17 2005/06/09 15:31:23 wolf31o2 Exp $
+# $Header: /var/cvsroot/gentoo/src/livecd-tools/net-setup,v 1.18 2006/05/30 19:50:59 wolf31o2 Exp $
 
 if [ -f /sbin/livecd-functions.sh ]
 then
 	source /sbin/livecd-functions.sh
 else
 	echo "ERROR: /sbin/livecd-functions.sh could not be loaded!"
+	exit 1
+fi
+
+if [ ! -x $(which dialog) ]
+then
+	echo "ERROR: The dialog utility is required for net-setup.  Exiting!"
 	exit 1
 fi
 
