Updated to have the same coding style, moved functions from each script into livecd-functions.sh, and cleaned up function names.

diff --git a/src/livecd-tools/x-setup b/src/livecd-tools/x-setup
--- a/src/livecd-tools/x-setup
+++ b/src/livecd-tools/x-setup
@@ -1,7 +1,7 @@
 #!/bin/bash
-# Copyright 1999-2004 Gentoo Technologies, Inc.
+# Copyright 1999-1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.13 2005/04/12 21:25:21 wolf31o2 Exp $
+# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.14 2005/05/16 19:26:39 wolf31o2 Exp $
 
 # Check for an xorg.conf
 if [ ! -e /etc/X11/xorg.conf ]
@@ -10,11 +10,21 @@ then
 	exit 1
 fi
 
+if [ -f /sbin/livecd-functions.sh ]
+then
+	source /sbin/livecd-functions.sh
+else
+	echo "ERROR: /sbin/livecd-functions.sh could not be loaded!"
+	exit 1
+fi
+
+livecd_check_root || exit 1
+
 #first, get paths right if we're getting started b4 login
 source /etc/profile
 
-echo "0" > /proc/sys/kernel/printk
-CMDLINE="`cat /proc/cmdline`"
+livecd_get_cmdline || exit 1
+
 for x in $CMDLINE
 do
         if [ "$x" = "agpgart" ]
@@ -23,63 +33,7 @@ do
         fi
 done
 
-no_gl() {
-	echo "No OpenGL-capable card found."
-	GLTYPE=xorg-x11
-}
-
-ati_gl() {
-	echo "ATI card detected."
-	GLTYPE=ati
-}
-
-nv_gl() {
-	echo "NVIDIA card detected."
-	GLTYPE=nvidia
-}
-
-get_video_cards() {
-	VIDEO_CARDS=`/sbin/lspci | grep VGA`
-	NUM_CARDS=`echo ${VIDEO_CARDS} | wc -l`
-	if [ ${NUM_CARDS} -eq 1 ]; then
-		NVIDIA=`echo ${VIDEO_CARDS} | grep "nVidia Corporation"`
-		ATI=`echo ${VIDEO_CARDS} | grep "ATI Technologies"`
-		if [ -n "${NVIDIA}" ]; then
-			NVIDIA_CARD=`echo ${NVIDIA} | awk 'BEGIN {RS=" "} /NV[0-9]+/ {print $1}'`
-			if [ -n "${NVIDIA_CARD}" ]; then
-				if [ `echo ${NVIDIA_CARD} | cut -dV -f2` -ge 4 ]; then
-					nv_gl
-				else
-					no_gl
-				fi
-			else
-				no_gl
-			fi
-		elif [ -n "${ATI}" ]; then
-			ATI_CARD=`echo ${ATI} | awk 'BEGIN {RS=" "} /(R|RV|RS)[0-9]+/ {print $1}'`
-			if [ `echo ${ATI_CARD} | grep S` ]; then
-				ATI_CARD_S=`echo ${ATI_CARD} | cut -dS -f2`
-			elif [ `echo ${ATI_CARD} | grep V` ]; then
-				ATI_CARD_V=`echo ${ATI_CARD} | cut -dV -f2`
-			else
-				ATI_CARD=`echo ${ATI_CARD} | cut -dR -f2`
-			fi
-			if [ -n "${ATI_CARD_S}" ] && [ ${ATI_CARD_S} -ge 350 ]; then
-				ati_gl
-			elif [ -n "${ATI_CARD_V}" ] && [ ${ATI_CARD_V} -ge 250 ]; then
-				ati_gl
-			elif [ -n "${ATI_CARD}" ] && [ ${ATI_CARD} -ge 200 ]; then
-				ati_gl
-			else
-				no_gl
-			fi
-		else
-			no_gl
-		fi
-	fi
-}
-
-get_video_cards
+get_video_cards || exit 1
 
 if [ -x /usr/sbin/opengl-update-livecd ]
 then
