Fixed net-setup and x-setup and also updated headers on all files.

diff --git a/src/livecd-tools/x-setup b/src/livecd-tools/x-setup
--- a/src/livecd-tools/x-setup
+++ b/src/livecd-tools/x-setup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2004 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.11 2005/03/01 01:26:08 wolf31o2 Exp $
+# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.12 2005/03/01 18:13:51 wolf31o2 Exp $
 
 # Check for an xorg.conf
 if [ ! -e /etc/X11/xorg.conf ]
@@ -28,6 +28,16 @@ no_gl() {
 	GLTYPE=xorg-x11
 }
 
+ati_gl() {
+	echo "ATI card detected."
+	GLTYPE=ati
+}
+
+nv_gl() {
+	echo "NVIDIA card detected."
+	GLTYPE=nvidia
+}
+
 get_video_cards() {
 	VIDEO_CARDS=`/sbin/lspci | grep VGA`
 	NUM_CARDS=`echo ${VIDEO_CARDS} | wc -l`
@@ -38,8 +48,7 @@ get_video_cards() {
 			NVIDIA_CARD=`echo ${NVIDIA} | awk 'BEGIN {RS=" "} /NV[0-9]+/ {print $1}'`
 			if [ -n "${NVIDIA_CARD}" ]; then
 				if [ `echo ${NVIDIA_CARD} | cut -dV -f2` -ge 4 ]; then
-					echo "NVIDIA card detected."
-					GLTYPE=nvidia
+					nv_gl
 				else
 					no_gl
 				fi
@@ -47,16 +56,20 @@ get_video_cards() {
 				no_gl
 			fi
 		elif [ -n "${ATI}" ]; then
-			ATI_CARD=`echo ${ATI} | awk 'BEGIN {RS=" "} /(R|RV|RS)\d{3}/ {print $1}'`
-			if [ -n "${ATI_CARD}" ]; then
-				if [ `echo ${ATI_CARD} | cut -dS -f2` -ge 350 ] || \
-					[ `echo ${ATI_CARD} | cut -dV -f2` -ge 250 ] || \
-					[ `echo ${ATI_CARD} | cut -dR -f2` -ge 200 ]; then
-						echo "ATI card detected."
-						GLTYPE=ati
-				else
-					no_gl
-				fi
+			ATI_CARD=`echo ${ATI} | awk 'BEGIN {RS=" "} /(R|RV|RS)[0-9]+/ {print $1}'`
+			if [ `echo ${ATI_CARD} | grep S` ]; then
+				ATI_CARD_S=`echo ${ATI_CARD} | cut -dS -f2`
+			elif [ `echo ${ATI_CARD} | grep V` ]; then
+				ATI_CARD_V=`echo ${ATI_CARD} | cut -dV -f2`
+			else
+				ATI_CARD=`echo ${ATI_CARD} | cut -dR -f2`
+			fi
+			if [ -n "${ATI_CARD_S}" ] && [ ${ATI_CARD_S} -ge 350 ]; then
+				ati_gl
+			elif [ -n "${ATI_CARD_V}" ] && [ ${ATI_CARD_V} -ge 250 ]; then
+				ati_gl
+			elif [ -n "${ATI_CARD}" ] && [ ${ATI_CARD} -ge 200 ]; then
+				ati_gl
 			else
 				no_gl
 			fi
@@ -71,8 +84,12 @@ get_video_cards
 if [ -x /usr/sbin/opengl-update-livecd ]
 then
 	/usr/sbin/opengl-update-livecd $GLTYPE
-else
+elif [ -x /usr/sbin/opengl-update ]
+then
 	opengl-update $GLTYPE
+else
+	echo "ERROR: no opengl-update script can be located"
+	exit 1
 fi
 
 #exec /usr/bin/xinit
