Added check for xorg.conf and changed sed line to xorg.conf.

diff --git a/src/livecd-tools/x-setup b/src/livecd-tools/x-setup
--- a/src/livecd-tools/x-setup
+++ b/src/livecd-tools/x-setup
@@ -1,7 +1,14 @@
 #!/bin/bash
 # Copyright 1999-2004 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.4 2004/11/19 16:11:24 wolf31o2 Exp $
+# $Header: /var/cvsroot/gentoo/src/livecd-tools/x-setup,v 1.5 2005/02/03 12:25:48 wolf31o2 Exp $
+
+# Check for an xorg.conf
+if [ ! -e /etc/X11/xorg.conf ]
+then
+	echo "ERROR: /etc/X11/xorg.conf cannot be found! Exiting"
+	exit 1
+fi
 
 #first, get paths right if we're getting started b4 login
 source /etc/profile
@@ -75,6 +82,6 @@ sed -i -e "s:##MOUSEPROTO##:${XMOUSETYPE}:" \
 	-e "s:##VERTREFRESH##:${VERTREFRESH}:" \
 	-e "s:##HORIZSYNC##:${HORIZSYNC}:" \
 	-e "s:DefaultColorDepth 16:DefaultColorDepth 24:" \
-	/etc/X11/XF86Config-4
+	/etc/X11/xorg.conf
 
 #exec /usr/X11R6/bin/xinit
