fixed command line arguments

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.2 2003/09/10 19:24:26 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.3 2003/09/11 14:21:36 zhen Exp $
 
 # please note that you SHOULD not tinker with variables in here unless
 # you ABSOLUTELY know what you are doing. Please use files/catalyst.conf instead.
@@ -179,15 +179,28 @@ prechecks() {
 		eerror "$0: This script requires root privileges to operate."
 		exit 1
 	fi
-
-	if [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
+	
+	is_special
+	if [ retval = 0 ]
 	then
-		eerror
-		eerror "Hardened profile not found in /usr/portage/profiles."
-		eerror "The hardened profile is a local profile and must be installed manually."
-		eerror "Please go to http://dev.gentoo.org/~zhen/Hardnened/profile to get the latest profile."
-		eerror
-		exit 1
+		if [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
+		then
+			eerror
+			eerror "Hardened profile (hardened-${MAINARCH}-${MAINVERSION} not found in /usr/portage/profiles."
+			eerror "The hardened profile is a local profile and must be installed manually."
+			eerror "Please go to http://dev.gentoo.org/~zhen/Hardnened/profile to get the latest profile."
+			eerror
+			exit 1
+		fi
+	fi
+}
+
+is_special() {
+	if [ $1 -e "snap" ] || [ $1 -e "enter" ] || [ $1 -e "umount" ]
+	then
+		return 1
+	else
+		return 0
 	fi
 }
 
