changes to how catalyst handles cmd line opts

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,10 +1,10 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.15 2003/09/21 19:35:03 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.16 2003/09/21 19:51:42 zhen Exp $
 
 # source the config file
-VERSION="1.0"
+VERSION="1.1"
 
 if [ -e files/catalyst.conf ]
 then
@@ -17,6 +17,16 @@ fi
 source /sbin/functions.sh
 
 SNAPBALL=${SNAPDIR}/portage-${4}.tar.bz2
+
+# unset so chroot doesn't get our custom setting
+unset PORTDIR DISTDIR
+[ ! -e "$MY_PORTDIR" ] && die "Portage dir $MY_PORTDIR not found, exiting."
+[ ! -e "$MY_DISTDIR" ] && die "Distdir $MY_DISTDIR not found; exiting."
+
+MY_DIST_LOCALS=${BASEDIR}/dists/${4}
+install -d $MY_DIST_LOCALS
+[ "$TMPDIR" = "" ] && CHROOTDIR="/var/tmp/catalyst/build/stage-${2}-${4}" || CHROOTDIR="$TMPDIR/stage-${2}-${4}"
+
 
 usage() {
 	einfo "Copyright 2003, Gentoo Technologies. Licensed under the GPL v2"
@@ -32,18 +42,24 @@ usage() {
 }
 
 prechecks() {
-	if [ "`whoami`" != "root" ]
+	if [ "$1" = "-h" ] || [ "$1" = "--help" ]
 	then
-		eerror "$0: This script requires root privileges to operate."
+		usage
 		exit 1
 	fi
-
+	
 	if [ -z $1 ]
 	then
 		usage
 		exit 1
 	fi
 
+	if [ "`whoami`" != "root" ]
+	then
+		eerror "$0: This script requires root privileges to operate."
+		exit 1
+	fi
+	
 	retval=is_special
 
 	if [ -z $retval ] && [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
@@ -527,12 +543,6 @@ EOF
 
 ## START MAIN PROGRAM ##
 
-if [ "$1" = "-h" ] || [ "$1" = "--help" ]
-then
-	usage
-	exit 1
-fi
-
 # more or less a sanity check
 prechecks $1
 
@@ -544,15 +554,6 @@ fi
 
 # all of the special preconditions should be filled, so start
 # the body of the program now
-
-# unset so chroot doesn't get our custom setting
-unset PORTDIR DISTDIR
-[ ! -e "$MY_PORTDIR" ] && die "Portage dir $MY_PORTDIR not found, exiting."
-[ ! -e "$MY_DISTDIR" ] && die "Distdir $MY_DISTDIR not found; exiting."
-
-MY_DIST_LOCALS=${BASEDIR}/dists/${4}
-install -d $MY_DIST_LOCALS
-[ "$TMPDIR" = "" ] && CHROOTDIR="/var/tmp/catalyst/build/stage-${2}-${4}" || CHROOTDIR="$TMPDIR/stage-${2}-${4}"
 
 get_arch $1 $2 $4
 pre_build $2 $3 $4
