some python integration (ongoing)

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,21 +1,20 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.27 2003/10/10 01:33:53 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.28 2003/10/11 19:28:46 drobbins Exp $
 
 VERSION="2.1"
 
-if [ -e files/catalyst.conf ]
-then
-	source files/catalyst.conf
-else
-	eerror"!!! Config file ${BASEDIR}files/catalyst.conf not found!!"
-	exit 1
-fi
-
 source /sbin/functions.sh
-source ${BASEDIR}/include/build_functions.sh
-source ${BASEDIR}/include/functions.sh
+source include/functions.sh
+source include/build_functions.sh
+[ -e files/catalyst.conf ] && source files/catalyst.conf || die "Config file files/catalyst.conf not found."
+
+
+rm -f /tmp/catalyst-subarches
+include/catalyst-subarches > /tmp/catalyst-subarches
+source /tmp/catalyst-subarches
+
 
 SNAPBALL=${SNAPDIR}/portage-${4}.tar.bz2
 
@@ -78,7 +77,7 @@ fi
 case "$1" in
 	"-h"|"--help")
 		usage
-		exit1
+		exit 1
 	;;
 
 	"snap")
@@ -104,7 +103,15 @@ esac
 ## START MAIN PROGRAM ##
 
 # more or less a sanity check
-get_arch $1 $2 $4
+SUBARCH=$1
+DESTSTAGE="${2}"
+DESTVER="${3}"
+SRCFORTAR=${CHROOTDIR}
+rm -f /tmp/catalyst.settings
+include/catalyst-settings $SUBARCH > /tmp/catalyst.settings
+source /tmp/catalyst.settings
+CFLAGS="${CFLAGS} -pipe"
+echo $CFLAGS
 pre_build $2 $3 $4
 build $2
 post_build $2
