added a get_arch function

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.9 2003/09/15 16:59:03 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.10 2003/09/15 17:43:30 zhen Exp $
 
 # source the config file
 VERSION="1.0"
@@ -29,6 +29,34 @@ usage() {
 	einfo "Valid stage targets: [0|1|2|3]" 
 	einfo "Valid stage target architectures: "
 	echo "${SUBARCHES}"
+}
+
+prechecks() {
+	if [ "`whoami`" != "root" ]
+	then
+		eerror "$0: This script requires root privileges to operate."
+		exit 1
+	fi
+
+	if [ -z $1 ]
+	then
+		usage
+		exit 1
+	fi
+
+	retval=is_special
+
+	if [ -z $retval ] && [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
+	then
+		eerror
+		eerror "!!! Hardened profile (hardened-${MAINARCH}-${MAINVERSION}) not found in /usr/portage/profiles."
+		eerror "!!! The hardened profile is a local profile and must be installed manually."
+		eerror "!!! Please go to http://dev.gentoo.org/~zhen/Hardnened/profile to get the latest profile."
+		eerror
+		exit 1
+	fi
+
+	unset retval
 }
 
 umount_all() {
@@ -95,7 +123,6 @@ makeconf() {
 
 print_build() { 
 	einfo "Gentoo Hardened stager (Catalyst) V${VERSION} starting."
-	echo 
 	einfo "Tarball Settings:"
 	einfo " Architecture: ${MAINARCH}"
 	einfo " Sub-architecture: ${SUBARCH}"
@@ -103,35 +130,6 @@ print_build() {
 	einfo " CHOST: ${CHOST}"
 	einfo " Source tarball: ${SRCBALL}"
 	einfo " Portage snapshot: ${SNAPBALL}"
-	echo
-}
-
-prechecks() {
-	if [ "`whoami`" != "root" ]
-	then
-		eerror "$0: This script requires root privileges to operate."
-		exit 1
-	fi
-
-	if [ -z $1 ]
-	then
-		usage
-		exit 1
-	fi
-
-	retval=is_special
-
-	if [ -z $retval ] && [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
-	then
-		eerror
-		eerror "!!! Hardened profile (hardened-${MAINARCH}-${MAINVERSION}) not found in /usr/portage/profiles."
-		eerror "!!! The hardened profile is a local profile and must be installed manually."
-		eerror "!!! Please go to http://dev.gentoo.org/~zhen/Hardnened/profile to get the latest profile."
-		eerror
-		exit 1
-	fi
-
-	unset retval
 }
 
 is_special() {
@@ -180,6 +178,124 @@ check_special() {
 		umount_all
 		exit 0
 	fi
+}
+
+get_arch() {
+	case "${1}" in
+	amd64)
+		MAINARCH="amd64"
+		CFLAGS="-O2 -fPIC"
+		CHOST="x86_64-pc-linux-gnu"
+	;;
+	
+	hppa|hppa1.1|hppa2.0)
+		MAINARCH="hppa"
+		case "${1}" in
+			hppa|hppa1.1)
+				CFLAGS="-march=1.1"
+		;;
+			hppa2.0)
+				CLAGS="-march=2.0"
+		;;
+		esac
+		CHOST="hppa-unknown-linux-gnu"
+		CFLAGS="-O2 $CFLAGS"
+	;;
+	
+	x86|i386|i486|i586|i686|athlon|athlon-xp|athlon-mp|pentium-mmx|pentium3|pentium4 )
+		MAINARCH="x86"
+		if [ "${1}" = "x86" ]
+		then
+			CFLAGS="-O3 -mcpu=i686"
+		elif [ "${1}" = "athlon-mp" ]
+		then
+			#MP and XP are functionally equivalent
+			CFLAGS="-O3 -march=athlon-xp"
+		else
+			CFLAGS="-O3 -march=${1} -fprefetch-loop-arrays"
+		fi
+		
+		# please don't touch these additional optimizations without consulting
+		# either zhen or drobbins
+		CFLAGS="$CFLAGS -funroll-loops"
+		case "${1}" in
+			i386|i486|i586)
+				CHOST="${1}-pc-linux-gnu"
+				;;
+			x86)
+				CHOST="i486-pc-linux-gnu"
+				;;
+			*)
+				CHOST=i686-pc-linux-gnu
+				;;
+		esac
+		
+		case "${1}" in
+			athlon|pentium-mmx|pentium3|pentium4 )
+				CFLAGS="$CFLAGS -fprefetch-loop-arrays"
+				;;
+		esac
+		;;
+	
+	ppc|g3|g4 )
+		MAINARCH="ppc"
+		CHOST="powerpc-unknown-linux-gnu"
+		CFLAGS="-O2 -fsigned-char"
+		if [ "${1}" = "g3" ]
+		then
+			CFLAGS="-O2 -mcpu=750 -mpowerpc-gfxopt -fsigned-char"
+		elif [ "${1}" = "g4" ]
+		then
+			CFLAGS="-O2 -mcpu=7400 -maltivec -mabi=altivec -mpowerpc-gfxopt -fsigned-char"
+		fi
+		;;
+	
+	sparc|sparc64 )
+		MAINARCH="${1}"
+		CHOST="sparc-unknown-linux-gnu"
+		CFLAGS=""
+		if [ "$1" = "sparc" ]
+		then
+			CFLAGS="-O2"
+		else
+			CFLAGS="-O3 -mcpu=ultrasparc -mtune=ultrasparc"
+		fi
+		;;
+	
+	mips )
+		MAINARCH="mips"
+		CHOST="mips-unknown-linux-gnu"
+		CFLAGS="-O2"
+		;;
+	
+	alpha|ev4|ev5|ev56|pca56|ev6|ev67 )
+		MAINARCH="alpha"
+		if [ "${1}" = "alpha" ]
+		then
+		        # defaults to ev5 code, which runs on anything
+			CHOST="alpha-unknown-linux-gnu"
+			CFLAGS="-O3 -mcpu=ev5"
+		else
+			CHOST="alpha${1}-linux-gnu"
+			CFLAGS="-O3 -mcpu=${1}"
+		fi
+		;;
+
+	* )
+		usage
+	;;
+	esac
+
+	if [ "${SUBARCH}" = "athlon-mp" ]
+	then
+		SUBARCH=athlon-xp
+	else
+		SUBARCH="${1}"
+	fi
+	DESTSTAGE="${2}"
+	DESTVER="${3}"
+	CFLAGS="${CFLAGS} -pipe"
+	SRCFORTAR=${CHROOTDIR}
 }
 
 pre_build() {
@@ -402,6 +518,8 @@ EOF
 	einfo "Build Complete!"
 }
 
+## START MAIN PROGRAM ##
+
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]
 then
 	usage
@@ -429,122 +547,7 @@ MY_DIST_LOCALS=${BASEDIR}/dists/${4}
 install -d $MY_DIST_LOCALS
 [ "$TMPDIR" = "" ] && CHROOTDIR="/var/tmp/catalyst/build/stage-${2}-${4}" || CHROOTDIR="$TMPDIR/stage-${2}-${4}"
 
-case "${1}" in
-	amd64)
-		MAINARCH="amd64"
-		CFLAGS="-O2 -fPIC"
-		CHOST="x86_64-pc-linux-gnu"
-	;;
-	
-	hppa|hppa1.1|hppa2.0)
-		MAINARCH="hppa"
-		case "${1}" in
-			hppa|hppa1.1)
-				CFLAGS="-march=1.1"
-		;;
-			hppa2.0)
-				CLAGS="-march=2.0"
-		;;
-		esac
-		CHOST="hppa-unknown-linux-gnu"
-		CFLAGS="-O2 $CFLAGS"
-	;;
-	
-	x86|i386|i486|i586|i686|athlon|athlon-xp|athlon-mp|pentium-mmx|pentium3|pentium4 )
-		MAINARCH="x86"
-		if [ "${1}" = "x86" ]
-		then
-			CFLAGS="-O3 -mcpu=i686"
-		elif [ "${1}" = "athlon-mp" ]
-		then
-			#MP and XP are functionally equivalent
-			CFLAGS="-O3 -march=athlon-xp"
-		else
-			CFLAGS="-O3 -march=${1} -fprefetch-loop-arrays"
-		fi
-		
-		# please don't touch these additional optimizations without consulting
-		# either zhen or drobbins
-		CFLAGS="$CFLAGS -funroll-loops"
-		case "${1}" in
-			i386|i486|i586)
-				CHOST="${1}-pc-linux-gnu"
-				;;
-			x86)
-				CHOST="i486-pc-linux-gnu"
-				;;
-			*)
-				CHOST=i686-pc-linux-gnu
-				;;
-		esac
-		
-		case "${1}" in
-			athlon|pentium-mmx|pentium3|pentium4 )
-				CFLAGS="$CFLAGS -fprefetch-loop-arrays"
-				;;
-		esac
-		;;
-	
-	ppc|g3|g4 )
-		MAINARCH="ppc"
-		CHOST="powerpc-unknown-linux-gnu"
-		CFLAGS="-O2 -fsigned-char"
-		if [ "${1}" = "g3" ]
-		then
-			CFLAGS="-O2 -mcpu=750 -mpowerpc-gfxopt -fsigned-char"
-		elif [ "${1}" = "g4" ]
-		then
-			CFLAGS="-O2 -mcpu=7400 -maltivec -mabi=altivec -mpowerpc-gfxopt -fsigned-char"
-		fi
-		;;
-	
-	sparc|sparc64 )
-		MAINARCH="${1}"
-		CHOST="sparc-unknown-linux-gnu"
-		CFLAGS=""
-		if [ "$1" = "sparc" ]
-		then
-			CFLAGS="-O2"
-		else
-			CFLAGS="-O3 -mcpu=ultrasparc -mtune=ultrasparc"
-		fi
-		;;
-	
-	mips )
-		MAINARCH="mips"
-		CHOST="mips-unknown-linux-gnu"
-		CFLAGS="-O2"
-		;;
-	
-	alpha|ev4|ev5|ev56|pca56|ev6|ev67 )
-		MAINARCH="alpha"
-		if [ "${1}" = "alpha" ]
-		then
-		        # defaults to ev5 code, which runs on anything
-			CHOST="alpha-unknown-linux-gnu"
-			CFLAGS="-O3 -mcpu=ev5"
-		else
-			CHOST="alpha${1}-linux-gnu"
-			CFLAGS="-O3 -mcpu=${1}"
-		fi
-		;;
-
-	* )
-		usage
-	;;
-esac
-
-if [ "${SUBARCH}" = "athlon-mp" ]
-then
-	SUBARCH=athlon-xp
-else
-	SUBARCH="${1}"
-fi
-DESTSTAGE="${2}"
-DESTVER="$4"
-CFLAGS="${CFLAGS} -pipe"
-SRCFORTAR=${CHROOTDIR}
-
+get_arch $1 $2 $4
 pre_build $2 $3 $4
 build $2
 post_build $2
