still borked

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,26 +1,21 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.4 2003/09/14 17:29:43 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.5 2003/09/14 22:56:33 zhen Exp $
 
-# please note that you SHOULD not tinker with variables in here unless
-# you ABSOLUTELY know what you are doing. Please use files/catalyst.conf instead.
-
+# source the config file
 VERSION="1.0"
-BASEDIR=`pwd`
-CONFIG=${BASEDIR}/files/catalyst.conf
-DESTBALL=${BASEDIR}/stages/stage${2}-${DESTARCH}-h-${4}.tar.bz2
-SRCBALL=${BASEDIR}/stages/stage${SRCSTAGE}-${SRCARCH}-h-${SRCVER}.tar.bz2
 
-if [ -e ${CONFIG} ]
+if [ -e files/catalyst.conf ]
 then
-	source ${CONFIG}
+	source files/catalyst.conf
 else
-	eerror"!!! Config file ${CONFIG} not found!!"
+	eerror"!!! Config file ${BASEDIR}files/catalyst.conf not found!!"
 	exit 1
 fi
 
 source /sbin/functions.sh
+
 
 usage() {
 	einfo "Copyright 2003, Gentoo Technologies. Licensed under the GPL v2"
@@ -84,11 +79,11 @@ unpack() {
 }
 
 tardir() {
-	echo -n "Creating ${DESTBALL}..."
+	ebegin "Creating ${DESTBALL}..."
 	cd ${SRCFORTAR} || die "Couldn't chdir; exiting."
 	tar -cjf ${DESTBALL} . --numeric-owner || die "Tarball creation error; exiting."
 	cd ${BASEDIR}
-	echo " done."
+	end " done."
 }
 
 makeconf() {
@@ -110,6 +105,59 @@ print_build() {
 }
 
 pre_build() {
+	case $2 in
+		1)
+			SRCSTAGE=2
+			SRCVER=${3}
+			SRCARCH=${MAINARCH}
+			DESTARCH=${MAINARCH}
+			SRCFORTAR=${CHROOTDIR}/tmp/stage1root
+		;;
+		2)
+			SRCSTAGE=1
+			SRCVER=${3}
+			SRCARCH=${MAINARCH}
+			DESTARCH=${SUBARCH}
+		;;
+		3)
+			SRCSTAGE=2
+			SRCVER=${3}
+			SRCARCH=${SUBARCH}
+			DESTARCH=${SUBARCH}
+		;;
+		grp)
+			SRCSTAGE=3
+			SRCVER=${3}
+			SRCARCH=${SUBARCH}
+			DESTARCH=${SUBARCH}
+		;;
+
+	esac
+	if [ "$2" = "grp" ]
+	then
+		MY_PKGDIR="${BASEDIR}/packages/grp-${DESTARCH}-${DESTVER}"
+	else
+		MY_PKGDIR="${BASEDIR}/packages/stage${DESTSTAGE}-${DESTARCH}-${DESTVER}"
+	fi
+	install -d ${STAGEDIR} ${MY_PKGDIR} ${SNAPDIR}
+
+	if [ "`uname -m`" = "x86_64" -a "$MAINARCH" = "x86" ]
+	then
+		if [ ! -e /bin/linux32 ]
+		then
+			eerror "Can't find linux32 executable. Please emerge sys-apps/linux32"
+			eerror "and try again."
+			die "linux32 not found; aborting."
+		fi
+		CHROOT="linux32 chroot"
+	else
+		CHROOT=chroot
+	fi
+	
+	# necessary internal definitions
+	DESTBALL="${BASEDIR}/stages/stage${2}-${DESTARCH}-h-${4}.tar.bz2"
+	SRCBALL="${BASEDIR}/stages/stage${SRCSTAGE}-${SRCARCH}-h-${SRCVER}.tar.bz2"
+
 	einfo "Cleaning up build directory..."
 	rm -rf ${CHROOTDIR}
 	install -d ${CHROOTDIR}
@@ -179,15 +227,34 @@ prechecks() {
 		eerror "$0: This script requires root privileges to operate."
 		exit 1
 	fi
-	
-	if [ $1 -e "snap" ] || [ $1 -e "enter" ] || [ $1 -e "umount" ] && [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
+
+	if [ -z $1 ]
+	then
+		usage
+		exit 1
+	fi
+
+	retval=is_special
+
+	if [ -z $retval ] && [ ! -d /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ]
 	then
 		eerror
-		eerror "!!! Hardened profile (hardened-${MAINARCH}-${MAINVERSION} not found in /usr/portage/profiles."
+		eerror "!!! Hardened profile (hardened-${MAINARCH}-${MAINVERSION}) not found in /usr/portage/profiles."
 		eerror "!!! The hardened profile is a local profile and must be installed manually."
 		eerror "!!! Please go to http://dev.gentoo.org/~zhen/Hardnened/profile to get the latest profile."
 		eerror
 		exit 1
+	fi
+
+	unset retval
+}
+
+is_special() {
+	if [ $1 -e "snap" -o $1 = "enter" -o $1 = "umount" ]
+	then
+		return 0
+	else
+		return 1
 	fi
 }
 
@@ -204,9 +271,9 @@ check_special() {
 		install -d ${CHROOTDIR}
 		einfo "Creating Portage tree snapshot..."	
 		rsync -a --exclude /packages/ --exclude /distfiles/ --exclude CVS/ ${MY_PORTDIR}/ ${CHROOTDIR}/portage/ || die
-		einfo -n "Creating Portage tree tarball..."
+		einfo "Creating Portage tree tarball..."
 		( cd $CHROOTDIR; tar cjf ${SNAPBALL} portage ) || die
-		echo " done."
+		einfo " done."
 		exit 0
 	fi
 
@@ -237,7 +304,7 @@ then
 fi
 
 # more or less a sanity check
-prechecks
+prechecks $1
 
 if [ "$1" = "enter" ] || [ "$1" = "umount" ] || [ "$1" = "snap" ]
 then
@@ -374,57 +441,8 @@ DESTVER="$4"
 CFLAGS="${CFLAGS} -pipe"
 SRCFORTAR=${CHROOTDIR}
 
-case "${2}" in
-	1)
-		SRCSTAGE=2
-		SRCVER=${3}
-		SRCARCH=${MAINARCH}
-		DESTARCH=${MAINARCH}
-		SRCFORTAR=${CHROOTDIR}/tmp/stage1root
-	;;
-	2)
-		SRCSTAGE=1
-		SRCVER=${3}
-		SRCARCH=${MAINARCH}
-		DESTARCH=${SUBARCH}
-	;;
-	3)
-		SRCSTAGE=2
-		SRCVER=${3}
-		SRCARCH=${SUBARCH}
-		DESTARCH=${SUBARCH}
-	;;
-	grp)
-		SRCSTAGE=3
-		SRCVER=${3}
-		SRCARCH=${SUBARCH}
-		DESTARCH=${SUBARCH}
-	;;
-
-esac
-if [ "$2" = "grp" ]
-then
-	MY_PKGDIR="${BASEDIR}/packages/grp-${DESTARCH}-${DESTVER}"
-else
-	MY_PKGDIR="${BASEDIR}/packages/stage${DESTSTAGE}-${DESTARCH}-${DESTVER}"
-fi
-install -d ${STAGEDIR} ${MY_PKGDIR} ${SNAPDIR}
-
-if [ "`uname -m`" = "x86_64" -a "$MAINARCH" = "x86" ]
-then
-	if [ ! -e /bin/linux32 ]
-	then
-		eerror "Can't find linux32 executable. Please emerge sys-apps/linux32"
-		eerror "and try again."
-		die "linux32 not found; aborting."
-	fi
-	CHROOT="linux32 chroot"
-else
-	CHROOT=chroot
-fi
-
 # prepare to build
-pre_build
+pre_build $2 $3
 
 case ${2} in
 	1)	
