still borked, but catalyst is almost working

diff --git a/users/zhen/catalyst/catalyst b/users/zhen/catalyst/catalyst
--- a/users/zhen/catalyst/catalyst
+++ b/users/zhen/catalyst/catalyst
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2003 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.5 2003/09/14 22:56:33 zhen Exp $
+# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.6 2003/09/14 23:43:45 zhen Exp $
 
 # source the config file
 VERSION="1.0"
@@ -40,7 +40,7 @@ umount_all() {
 
 die() {
 	#unmount filesystems if script is aborted
-	[ -n "${1}" ] && echo "${0}: error: ${1}"
+	[ -n "${1}" ] && einfo "${0}: error: ${1}"
 	umount_all 
 	exit 1
 }
@@ -57,7 +57,7 @@ mount_all() {
 		mount --bind ${x} ${CHROOTDIR}${x} || die "Couldn't bind-mount ${x}"
 	done
 	[ ! -e ${SNAPBALL} ] && die "Can't find $( basename $SNAPBALL ); exiting." 	
-	echo "Extracting Portage tree snapshot..."
+	einfo "Extracting Portage tree snapshot..."
 	tar xjf ${SNAPBALL} -C ${CHROOTDIR}/usr || die "Error extracting Portage snapshot"
 	[ ! -e ${CHROOTDIR}/usr/portage/packages ] && install -d ${CHROOTDIR}/usr/portage/packages
 	mount --bind ${MY_PKGDIR} ${CHROOTDIR}/usr/portage/packages || die
@@ -93,8 +93,8 @@ makeconf() {
 }
 
 print_build() { 
-	einfo "Gentoo Hardned stager (Catalyst) V${VERSION} starting."
-	einfo 
+	einfo "Gentoo Hardened stager (Catalyst) V${VERSION} starting."
+	echo 
 	einfo "Tarball Settings:"
 	einfo " Architecture: ${MAINARCH}"
 	einfo " Sub-architecture: ${SUBARCH}"
@@ -102,38 +102,39 @@ print_build() {
 	einfo " CHOST: ${CHOST}"
 	einfo " Source tarball: ${SRCBALL}"
 	einfo " Portage snapshot: ${SNAPBALL}"
+	echo
 }
 
 pre_build() {
-	case $2 in
+	case $1 in
 		1)
 			SRCSTAGE=2
-			SRCVER=${3}
+			SRCVER=${2}
 			SRCARCH=${MAINARCH}
 			DESTARCH=${MAINARCH}
 			SRCFORTAR=${CHROOTDIR}/tmp/stage1root
 		;;
 		2)
 			SRCSTAGE=1
-			SRCVER=${3}
+			SRCVER=${2}
 			SRCARCH=${MAINARCH}
 			DESTARCH=${SUBARCH}
 		;;
 		3)
 			SRCSTAGE=2
-			SRCVER=${3}
+			SRCVER=${2}
 			SRCARCH=${SUBARCH}
 			DESTARCH=${SUBARCH}
 		;;
 		grp)
 			SRCSTAGE=3
-			SRCVER=${3}
+			SRCVER=${2}
 			SRCARCH=${SUBARCH}
 			DESTARCH=${SUBARCH}
 		;;
 
 	esac
-	if [ "$2" = "grp" ]
+	if [ "$1" = "grp" ]
 	then
 		MY_PKGDIR="${BASEDIR}/packages/grp-${DESTARCH}-${DESTVER}"
 	else
@@ -155,7 +156,7 @@ pre_build() {
 	fi
 	
 	# necessary internal definitions
-	DESTBALL="${BASEDIR}/stages/stage${2}-${DESTARCH}-h-${4}.tar.bz2"
+	DESTBALL="${BASEDIR}/stages/stage${1}-${DESTARCH}-h-${2}.tar.bz2"
 	SRCBALL="${BASEDIR}/stages/stage${SRCSTAGE}-${SRCARCH}-h-${SRCVER}.tar.bz2"
 
 	einfo "Cleaning up build directory..."
@@ -166,7 +167,6 @@ pre_build() {
 	trap "die" INT QUIT 
 
 	umount_all
-	echo
 	[ ! -e ${SRCBALL} ] && die "Can't find source tarball ${SRCBALL}; exiting."
 	einfo "Unpacking ${SRCBALL}..."
 	unpack ${SRCBALL}
@@ -182,21 +182,24 @@ pre_build() {
 
 	#now, it's time to build...
 	cd ${CHROOTDIR}
-	rm etc/make.profile
+	if [ -e ${BASEDIR}/make.profile ]
+	then
+		rm ${BASEDIR}/make.profile
+	fi
 	# <zhen@gentoo.org> REMINDER: The hardened profile is a local one that I use. 
-	ln -sf /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ${BASEDIR}/etc/make.profile
+	ln -sf /usr/portage/profiles/hardened-${MAINARCH}-${MAINVERSION} ${BASEDIR}/make.profile
 	if [ ${CCACHE} > 0 ]
 	then
 		export FEATURES="ccache"
 	fi
 
-	if [ ${2} != "grp" ]
+	if [ ${1} != "grp" ]
 	then
 		einfo " Destination tarball: ${DESTBALL}"
 	else
 		einfo " Target: GRP build"
 	fi
-	echo "Build Settings:"
+	einfo "Build Settings:"
 	if [ ${CCACHE} > 0 ]
 	then
 		einfo " ccache support: Enabled"
@@ -206,14 +209,31 @@ pre_build() {
 }
 
 post_build() {
-	#umount all filesystems
+	case "$1" in
+	1)
+		$CHROOT . /tmp/stage1 clean /tmp/stage1root
+		;;
+	2|3)
+		$CHROOT . /bin/bash << EOF
+		if [ ${CCACHE} > 0 ]
+		then
+			emerge -C ccache
+		fi
+EOF
+		rm -rf ${CHROOTDIR}/tmp/* 
+		rm -rf ${CHROOTDIR}/var/tmp/portage/*
+		rm -f ${CHROOTDIR}/etc/ld.so.preload
+		;;
+	esac
+	
 	umount_all
+	
 	rm ${CHROOTDIR}/etc/resolv.conf
 	einfo "Removing Portage tree from chroot image..."
 	rm -rf ${CHROOTDIR}/usr/portage
 
 	#pack up directory to ${DESTBALL}
-	if [ "$2" != "grp" ]
+	if [ "$1" != "grp" ]
 	then
 		tardir
 	fi
@@ -263,7 +283,7 @@ check_special() {
 	if [ $1 = "snap" ]
 	then
 		[ "$TMPDIR" = "" ] && CHROOTDIR="/var/tmp/catalyst/build/snap-${2}" || CHROOTDIR="$TMPDIR/snap-${2}"
-		SNAPBALL=${SNAPDIR}/portage-${2}.tar.bz2
+		SNAPBALL=${BASEDIR}/${SNAPDIR}/portage-${2}.tar.bz2
 
 		install -d ${SNAPDIR}
 		einfo "Cleaning up build directory..."
@@ -295,6 +315,84 @@ check_special() {
 		umount_all
 		exit 0
 	fi
+}
+
+build() {
+	case ${1} in
+		1)	
+			cp ${BASEDIR}/bin/stage1 ${CHROOTDIR}/tmp
+			#CHOST is for the gcc-config initialization step
+			export MAINVERSION MAINARCH CHOST CCACHE
+			#get our make.conf instide our new tree
+			#good idea because make.conf should be there.
+			#also necessary because the "stage1" script runs gcc-config, which
+			#uses portage, which requires /etc/make.conf to exist.
+			makeconf ${CHROOTDIR}/tmp/stage1root
+			$CHROOT . /tmp/stage1 build /tmp/stage1root
+			[ $? -ne 0 ] && die "Stage 1 build failure"
+		;;
+		2)	
+			$CHROOT . /bin/bash << EOF
+			env-update
+			source /etc/profile
+			mkdir -p /usr/portage/packages/All
+			export EMERGE_OPTS="--usepkg --buildpkg"
+			if [ -n ${CCACHE} ]
+			then
+				emerge --oneshot --nodeps ccache || exit 1
+			fi
+			emerge --oneshot --nodeps hardened-gcc || exit 1
+			${BASEDIR}/bin/hardened-bootstrap.sh || exit 1
+EOF
+			[ $? -ne 0 ] && die "Stage 2 build failure"
+		;;
+		3)
+			$CHROOT . /bin/bash << EOF
+			env-update
+			source /etc/profile
+			if [ -n ${CCACHE} ]
+			then
+				emerge --oneshot --nodeps --usepkg --buildpkg ccache || exit 1
+			fi
+			emerge --oneshot --nodeps hardened-gcc || exit 1
+			export CONFIG_PROTECT="-*"
+			emerge system --usepkg --buildpkg || exit 1
+EOF
+			[ $? -ne 0 ] && die "Stage 3 build failure"
+		;;
+		grp) 
+			cp ${BASEDIR}/grp/${MAINARCH}.* ${CHROOTDIR}/tmp || die
+			$CHROOT . /bin/bash << EOF
+			env-update
+			source /etc/profile
+			export CONFIG_PROTECT="-*"
+			source /tmp/${MAINARCH}.conf
+			#add bindist for this part
+			export USE="\$USE bindist"
+			#CD 1 contains "base" packages: kernel sources, hardware, crons, loggers, X
+			export PKGDIR=/usr/portage/packages/cd1
+			for x in \$( cat /tmp/${MAINARCH}.pkg.cd1  | grep -v ^# )
+			do
+				emerge --noreplace --buildpkg --usepkg \$x || exit 1
+			done
+			#CD 2 contains application packages: GNOME, KDE, and others
+			export PKGDIR=/usr/portage/packages/cd2
+			for x in \$( cat /tmp/${MAINARCH}.pkg.cd2  | grep -v ^# )
+			do
+				emerge --noreplace --buildpkg --usepkg \$x || exit 1
+			done
+			source /tmp/${MAINARCH}.conf
+			#export GENTOO_MIRRORS="/usr/portage"
+			export DISTDIR="/var/tmp/distfiles"
+			install -d \$DISTDIR
+			for x in \$( cat /tmp/${MAINARCH}.src | grep -v ^# )
+			do
+				emerge --fetchonly \$x || exit 1
+			done
+EOF
+			[ $? -ne 0 ] && die "GRP build failure"
+			;;
+	esac
 }
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]
@@ -441,103 +539,8 @@ DESTVER="$4"
 CFLAGS="${CFLAGS} -pipe"
 SRCFORTAR=${CHROOTDIR}
 
-# prepare to build
-pre_build $2 $3
-
-case ${2} in
-	1)	
-		cp ${BASEDIR}/bin/stage1 ${CHROOTDIR}/tmp
-		#CHOST is for the gcc-config initialization step
-		export MAINVERSION MAINARCH CHOST CCACHE
-		#get our make.conf instide our new tree
-		#good idea because make.conf should be there.
-		#also necessary because the "stage1" script runs gcc-config, which
-		#uses portage, which requires /etc/make.conf to exist.
-		makeconf ${CHROOTDIR}/tmp/stage1root
-		$CHROOT . /tmp/stage1 build /tmp/stage1root
-		[ $? -ne 0 ] && die "Stage 1 build failure"
-	;;
-	2)	
-		$CHROOT . /bin/bash << EOF
-		env-update
-		source /etc/profile
-		mkdir -p /usr/portage/packages/All
-		export EMERGE_OPTS="--usepkg --buildpkg"
-		if [ ${CCACHE} > 0 ]
-		then
-			emerge --oneshot --nodeps ccache || exit 1
-		fi
-		emerge --oneshot --nodeps hardened-gcc || exit 1
-		${BASEDIR}/bin/hardened-bootstrap.sh || exit 1
-EOF
-		[ $? -ne 0 ] && die "Stage 2 build failure"
-	;;
-	3)
-		$CHROOT . /bin/bash << EOF
-		env-update
-		source /etc/profile
-		if [ ${CCACHE} > 0 ]
-		then
-			emerge --oneshot --nodeps --usepkg --buildpkg ccache || exit 1
-		fi
-		emerge --oneshot --nodeps hardened-gcc || exit 1
-		export CONFIG_PROTECT="-*"
-		emerge system --usepkg --buildpkg || exit 1
-EOF
-		[ $? -ne 0 ] && die "Stage 3 build failure"
-	;;
-	grp) 
-		cp ${BASEDIR}/grp/${MAINARCH}.* ${CHROOTDIR}/tmp || die
-		$CHROOT . /bin/bash << EOF
-		env-update
-		source /etc/profile
-		export CONFIG_PROTECT="-*"
-		source /tmp/${MAINARCH}.conf
-		#add bindist for this part
-		export USE="\$USE bindist"
-		#CD 1 contains "base" packages: kernel sources, hardware, crons, loggers, X
-		export PKGDIR=/usr/portage/packages/cd1
-		for x in \$( cat /tmp/${MAINARCH}.pkg.cd1  | grep -v ^# )
-		do
-			emerge --noreplace --buildpkg --usepkg \$x || exit 1
-		done
-		#CD 2 contains application packages: GNOME, KDE, and others
-		export PKGDIR=/usr/portage/packages/cd2
-		for x in \$( cat /tmp/${MAINARCH}.pkg.cd2  | grep -v ^# )
-		do
-			emerge --noreplace --buildpkg --usepkg \$x || exit 1
-		done
-		source /tmp/${MAINARCH}.conf
-		#export GENTOO_MIRRORS="/usr/portage"
-		export DISTDIR="/var/tmp/distfiles"
-		install -d \$DISTDIR
-		for x in \$( cat /tmp/${MAINARCH}.src | grep -v ^# )
-		do
-			emerge --fetchonly \$x || exit 1
-		done
-EOF
-		[ $? -ne 0 ] && die "GRP build failure"
-		;;
-esac
-
-#additional cleanup
-case "$2" in
-	1)
-		$CHROOT . /tmp/stage1 clean /tmp/stage1root
-		;;
-	2|3)
-		$CHROOT . /bin/bash << EOF
-		if [ ${CCACHE} > 0 ]
-		then
-			emerge -C ccache
-		fi
-EOF
-		rm -rf ${CHROOTDIR}/tmp/* 
-		rm -rf ${CHROOTDIR}/var/tmp/portage/*
-		rm -f ${CHROOTDIR}/etc/ld.so.preload
-		;;
-esac
-
-post_build
+pre_build $2 $3 $4
+build $2
+post_build $2
 
 # vim ts=4
