dont want to trigger an infinite loop #69543

diff --git a/src/wine/misc/wine-setup b/src/wine/misc/wine-setup
--- a/src/wine/misc/wine-setup
+++ b/src/wine/misc/wine-setup
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/wine-setup,v 1.1 2004/10/27 16:01:20 vapier Exp $
+# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/wine-setup,v 1.2 2004/10/31 00:51:23 vapier Exp $
 
 # Setup the Gentoo wine environment:
 #  - generate $WINEPREFIX with some sane defaults if need be
@@ -22,7 +22,10 @@ then
 	mkdir -p ${WINEPREFIX}/fake_windows
 
 	# First copy in the new config file.
-	cp "${INSTALLDIR}/share/wine/data/config" "${WINEPREFIX}/config"
+	if ! cp "${INSTALLDIR}/share/wine/data/config" "${WINEPREFIX}/config" ; then
+		echo "!! could not find ${INSTALLDIR}/share/wine/data/config"
+		exit 1
+	fi
 
 	echo "!! Setting up ~/.wine/fake_windows/"
 	cp -R ${INSTALLDIR}/share/wine/data/fake_windows/* ${WINEPREFIX}/fake_windows/
